version: "3.8"
services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    ports:
      - "5000:5000"
    volumes:
      - ./certs:/certs
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/domain.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/domain.key
      - DELETE_IMAGES=true
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    restart: always
